### ISSUE TITLE
Uncaught ReferenceError: Swal is not defined

### ISSUE THREAD

**Issue by ademir10** [Atrox/sweetify#10]
Hi Atrox! how are you doing?
I'm facing a strange problem after to format my Notebook..
Everything was working perfect using your gem, but now when i try to show some message, i have this in my log:

Uncaught ReferenceError: Swal is not defined
And i don't changed nothing..

I tried to run rails assets:precompile, and i checked if i have the code below in my application.html.erb, and everything is there.. 
Gem file:
gem 'sweetify'
gem 'rails-assets-sweetalert2', '~> 5.1.1', source: 'https://rails-assets.org'
gem 'sweet-alert2-rails'

application.js:
//= require sweetalert2
//= require sweet-alert2-rails

application.html.erb:
<%= render 'sweetify/alert' %>

Do you have some suggestion?
thanks!

**Comment by Atrox** [comment]
Hey,

it looks like you are using a old sweetalert2 version (5.1.1). You can update the library or you could also create a file `sweetify.rb` in your initializers with the following content:
```ruby
Sweetify.sweetalert_library = 'sweetalert'
```

**Comment by ademir10** [comment]
Thank you so much!
It's worked, but now in my log i have this warning messages:

body=1:479 SweetAlert2: Unknown parameter "icon"
body=1:479 SweetAlert2: Unknown parameter "closeOnClickOutside"
body=1:479 SweetAlert2: Unknown parameter "button"

Do you know what can i do to update my library? do you have some step by step about it?
Thanks again my dear friend!

**Comment by ademir10** [comment]
I tried to upgrade this Gem version to '6.0.1' or even to the last version, but no way:

gem 'rails-assets-sweetalert2', '~> 5.1.1', source: 'https://rails-assets.org'

there is another way to fix it?

**Comment by ademir10** [comment]
fixed!
after to remove and reinstall the gem: 'rails-assets-sweetalert2'
I reinstalled this version: gem 'rails-assets-sweetalert2', '~> 6.0.1', source: 'https://rails-assets.org'
after that i just changed the the sweetify.rb in inicializers to:
Sweetify.sweetalert_library = 'SweetAlert2'
And everything is working fine. 
Thank you my dear friend!

**Comment by Atrox** [comment]
Great to hear you got it working :)
