### ISSUE TITLE
Rails 6 - sweetify

### ISSUE THREAD

**Issue by geomcn11** [Atrox/sweetify#11]
Hi, I am trying to integrate sweetify into my rails 6 app using webpacker. Is it possible to do this? if so, I was wondering if you have a guide on how to do this. At the moment I am getting a swal is not defined error.

**Comment by Atrox** [comment]
Hey @geomcn11, it should just work out of the box.

In your application.js import sweetalert like this:
```javascript
import Swal from 'sweetalert2'
// set swal on window for sweetify
window.swal = Swal
```
