### ISSUE TITLE
Don't working in smartphones (environment production) - Rails 4

### ISSUE THREAD

**Issue by ademir10** [Atrox/sweetify#2]
Hi Guys, i dont know why, but my messages not working in production when i try using smartphones, but in development everything works fine.

And when i try using browsers in whatever SO works fine in production or development.

I did everything again and nothing change, this is my code:

APPLICATION.JS
//= require jquery
//= require jquery.min
//= require jquery_ujs
//= require jquery-ui
//= require autocomplete-rails
//= require bootstrap
//= require twitter/bootstrap
//= require bootstrap-datepicker
//= require bootstrap-datepicker/core
//= require maskedinput

//= require fusioncharts/fusioncharts
//= require fusioncharts/fusioncharts.charts
//= require fusioncharts/fusioncharts.theme.fint
//= require demo
//= require dash
//= require jquery.touchSwipe.min
//= require sweetalert
//= require dropzone
//= require bootstrap/modal
//= require_tree .

APPLICATION.HTML.ERB
 <%= javascript_include_tag 'demo', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'dash', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery.touchSwipe.min', 'data-turbolinks-track' => true %>
    <%= render 'sweetify/alert' %>

GEM FILE
source 'https://rubygems.org'
# para o dropzone images

gem 'paperclip'
gem 'dropzonejs-rails'
# para mensagens personalizadas em javascript

gem 'sweetalert-rails'
gem 'sweetalert2'
# para as flash messages

gem 'sweetify'
# para autocompletar na consulta do produto

gem 'rails4-autocomplete'
gem 'jquery-ui-rails'
# usando o thin server

gem 'thin'
# para gerar o grafico por mes

gem 'fusioncharts-rails'
# exportar para XLS

gem 'to_xls-rails'# Last officially released gem
# usando simple calendar

gem "simple_calendar", "~> 2.0"
# gerar os graficos

gem "chartkick"
# gems adicionadas para esse projeto manualmente

gem 'twitter-bootstrap-rails'

gem 'bootstrap-sass'
# só funciona instalando pelo prompt esse versão, e especificando abaixo a versão 3.1.10
# gem install bcrypt --platform=ruby

gem 'bcrypt', '3.1.11'
# paginar as paginas

gem 'will_paginate'
# envio de emails

gem 'actionmailer'
# carrega o datetime picker nas datas
# gem 'bootstrap-datepicker-rails', :require => 'bootstrap-datepicker-rails',
# :git => 'git://github.com/Nerian/bootstrap-datepicker-rails.git'

gem 'bootstrap-datepicker-rails'                              
# tive que adicionar essa gem para funcionar o jquery no heroku

gem 'rails_12factor'          
# pdf

gem 'wicked_pdf'
gem 'pdfkit'
gem 'wkhtmltopdf-binary'
gem 'responders'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record

gem 'pg', '~> 0.15'
# Use SCSS for stylesheets

gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets

gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views

gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use jquery as the JavaScript library

gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.

gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Help me please! thank you.

**Comment by Atrox** [comment]
Please try to put `<%= render 'sweetify/alert' %>` at the very bottom of your `application.html.erb`. Just before the end of `</body>`.

If this still does not work, please provide some sort of an example application. I'm not able to reproduce the issue on my machine and smartphone.

**Comment by ademir10** [comment]
thanks Atrox, solved! i found the error using javascript window.onerror
God bless you my friend!

**Comment by Atrox** [comment]
Great to hear. Let me know if there pop up any other issues with `sweetify`.
