### ISSUE TITLE
Sweetify Alert without redirect_to

### ISSUE THREAD

**Issue by GouthamSI** [Atrox/sweetify#3]
### This is more of a Query than an Issue.

Using the sweetify gem extensively in my project. However, I've a requirement to show the alert message on click of form submit, if there are any errors like duplicate data and etc. With redirect_to, i can able to easily display the sweetify alert message, but redirect_to is refreshing the page and thus clearing/resetting the form. Is there any way, i can use this alert mechanism without any redirect_to? Or is there any better way to address the problem? 
Any help or advice is well appreciated. Thanks in Advance.

Sample code: 
```
rescue ActiveRecord::ActiveRecordError => ex
 sweetalert_error(ex.message, 'Error! Failed to create a record.', persistent: 'OK')
 redirect_to new_records_path
```

**Comment by Atrox** [comment]
Hey,

instead of a redirect, just render the new records page. Something along this line:
```ruby
@record = Record.new(record_params)

if @record.save
    redirect_to record_path
else
    sweetalert_error(ex.message, 'Error! Failed to create a record.', persistent: 'OK')
    render :new
end
```

If you do it like this `@record` is still available to the template and all submitted data (and errors) are available in the template. Hope this helps!

**Comment by GouthamSI** [comment]
Thank you. `render :new` helped. But when I redirect or navigate to any other page, I'm getting the same alert message once again. Since the `<%= render 'sweetify/alert' %>` is there in `application.html.erb` file.

Can we nullify the sweetalert message or stop rendering again in the navigated page ?

Did `flash[:sweetify] = ""` after the `render :new` for a fix. Is there any better way to address this ?
