### ISSUE TITLE
Timer can´t be set

### ISSUE THREAD

**Issue by RubenGram** [Atrox/sweetify#4]
Hello, I've installed sweetify and tried to set the timer to 5 sec: 
`sweetalert_success('Your resource is created and available.', 'Successfully created', persistent: 'Awesome!', timer: 5000)`
But instead of disappearing, the alert stays there. Also, when I tried to get back to normal (deleting the 'timer: 5000' part) the default timer didn´t seemed to work anymore. Am I doing something wrong?

**Comment by Atrox** [comment]
Hey @RubenGram,

Use `button: 'Awesome!'` instead of `persistent: 'Awesome!'` if you still want the dialog to disappear after the set time.

As stated in the readme for `persistent`: 
> Shows the alert with a button and only closes if the button is pressed

**Comment by RubenGram** [comment]
Yeah, I just saw that obvious word for a remainig button (persistant), I'm sorry and thank you for your help!
