### ISSUE TITLE
Unhandled Promise Rejection: timer - Rails 5

### ISSUE THREAD

**Issue by ademir10** [Atrox/sweetify#5]
Hi Guys! I'm with a little problem here, everything is working fine, I just have this problem:
In my alert I have this code:
sweetalert_success('Bem vindo ' + current_user.name.to_s + "!", 'Olá!')
without timer and without button, the message appear but I have this message in my log:
Unhandled Promise Rejection: timer
And after to see this message my view stay freeze, and I can't do nothing, so when I press  F5 my view refresh and back to work until to appear other alert message..
Do you know what can I do to fix it?
Thanks!

**Comment by Atrox** [comment]
What version of SweetAlert are you using?

**Comment by ademir10** [comment]
Hi Atrox!, this is what I have in my Gem file:
Installing sweetify 1.0.0

**Comment by Atrox** [comment]
Hey :) I'm not talking about sweetify itself. I talk about SweetAlert, the javascript/css files. Which version of these are you currently using?

**Comment by ademir10** [comment]
sorry my friend, I have this guys in my gem file:
gem 'sweetify'
gem 'rails-assets-sweetalert2', '~> 5.1.1', source: 'https://rails-assets.org'
gem 'sweet-alert2-rails'

in my CSS file:
*= require sweetalert2

**Comment by Atrox** [comment]
I will take a look tomorrow

**Comment by ademir10** [comment]
Okay Atrox, thanks for help me!

**Comment by ademir10** [comment]
I don't know if this can help you Atrox, but when I see the code in log it's here the problem:

var container = getContainer();
  var modal = getModal();

  return new Promise(function (resolve, reject) {
    // Close on timer
    if (params.timer) {
      modal.timeout = setTimeout(function () {
        sweetAlert.closeModal(params.onClose);
        if (params.useRejections) {
          reject('timer');                <<<<<<<<<HERE IS THE PROBLEM
        } else {
          resolve({ dismiss: 'timer' });
        }
      }, params.timer);
    }

**Comment by ademir10** [comment]
Hi Atrox, how are you? do you found something about my issue? I still have the same problem when i try to use the alerts without buttons...
thanks.

**Comment by Atrox** [comment]
Hey! Sorry for the late response.

Could you please try the following:
```ruby
sweetalert_success('placeholder', 'placeholder', useRejections: false)
```

Note the `useRejections: false`

**Comment by ademir10** [comment]
Thanks for your help dude! I’m out today but when I back to the office I’ll try and I tell you. Hugs!
