### ISSUE TITLE
SweetAlert button options have changed

### ISSUE THREAD

**Issue by JonathanWThom** [Atrox/sweetify#6]
Hello! Thank you for making this gem, it works great. I noticed while using it that there were some deprecation warnings to do with button options.

<img width="1075" alt="screen shot 2018-03-24 at 12 44 59 pm" src="https://user-images.githubusercontent.com/22665228/37868310-6389d662-2f61-11e8-97bd-b63ef0724132.png">

The new button options are [here](https://sweetalert.js.org/docs/#button). If you're interested, I'd be happy to work on a PR to update the options hash and get rid of these warnings.

**Comment by artemrakov** [comment]
because warning "type" icons doesnt show up on the screen :(

**Comment by Atrox** [comment]
Hey, thank you for opening this issue.

I would love to support [sweetalert](https://github.com/t4t5/sweetalert) and [sweetalert2](https://github.com/sweetalert2/sweetalert2). Previously they both had the same API but now that sweetalert changed it with v2, we probably have to make it configurable somehow.

Happy to take suggestions on this part how we can do this best. Some people use sweetalert and some use sweetalert2, would love to make both parties happy.

**Comment by JonathanWThom** [comment]
Oh, of course! Silly of me to not realize that it was simply due to different versions of sweetalert. Sure enough, I'm running v2.1. I will see if I can get more familiar with the nuances of both versions of sweetalert and come up with an elegant way to handle both of them. Feel free to close this if you want.
