### ISSUE TITLE
auto closing message

### ISSUE THREAD

**Issue by ademir10** [Atrox/sweetify#7]
Hi Atrox! how are you?
Do you know if it's possible to insert autoclosing on the messages?
Because I'm using: "useRejections: false" but I receive this error: "Unhandled Promise Rejection: timer"

And looking in google I see that it happens because "useRejections"  are used in another gem called SweetAlert2.

Do you have any other suggestion?
Thanks!

**Comment by Atrox** [comment]
Hey, it looks like you are using an old version of SweetAlert2. What version of SweetAlert2 do you currently have installed?

**Comment by ademir10** [comment]
I’m using this versions to use the custom messages:

gem 'sweetify'
gem 'rails-assets-sweetalert2', source: 'https://rails-assets.org'
gem 'sweet-alert2-rails'



Ademir de Góes Gomes
Gerente de T.I / Consultor de Negócios

(11)4308-1643
(11)97039-5230
www.ddti.com.br  

Em 1 de abr de 2018, à(s) 07:03, Atrox <notifications@github.com> escreveu:

**Comment by Atrox** [comment]
Hey, I just tested this and it works fine for me. The dialog closes automatically, as it should, with no errors thrown.

Can you try to put an example application together with the occurring issue?

**Comment by ademir10** [comment]
Hi my friend! this is my code:
sweetalert_success('See you soon!', 'Bye!', useRejections: false)
This is a simple message, and this is my log in the browser:
Unhandled Promise Rejection: timer

it happens in chrome and also in Safari.
Any suggestion? thanks!

**Comment by Unayung** [comment]
Hi @ademir10 . I'm not sure if you still had this Rejection: timer issue.

when I switched to older version of rails-assets-sweetalert2 like 7-ish
gem 'sweetify'
gem 'rails-assets-sweetalert2', '~> 7', source: 'https://rails-assets.org'
gem 'sweet-alert2-rails'

it works great without any error or warning : )

**Comment by ademir10** [comment]
Hi Chen!
I’ll try it tomorrow, I’m still with this same problem in one of my projects.

Thank you for the tip man! 

Ademir de Góes Gomes
Gerente de T.I / Consultor de Negócios

(11)4308-1643
(11)97039-5230
www.ddti.com.br  

Em 5 de mai de 2019, à(s) 04:18, Chen Chia Yang <notifications@github.com> escreveu:

**Comment by Atrox** [comment]
Hey,

I just pushed `v2.0.0`. This now allows you to use both sweetalert and sweetalert2 with sweetify. Just specify which one you are using:
```ruby
# Next up, create the file sweetify.rb in your initializers to specify the library you are using (SweetAlert or SweetAlert2):

# possible options: 'sweetalert', 'sweetalert2' - default is 'sweetalert2'
Sweetify.sweetalert_library = 'sweetalert2'
```

This should resolve the problem and allows you to use the newest version of sweetalert2 (or sweetalert).
