### ISSUE TITLE
Swal is not defined

### ISSUE THREAD

**Issue by ademir10** [Atrox/sweetify#9]
Hi, I'm trying to implement your Gem in my Rails App and i dont know why i'm receiving this error:

Uncaught ReferenceError: Swal is not defined

I did everything:
APPLICATION.JS
//= require jquery
//= require bootstrap
//= require jquery_ujs
//=require jquery.turbolinks
//= require jquery-ui
//= require twitter/bootstrap
//= require autocomplete-rails
//= require turbolinks
//= require underscore
//= require gmaps/google
//= require rails-ujs
//= require sweetalert2
//= require sweet-alert2-rails
//= require chartkick
//= require fusioncharts/fusioncharts
//= require fusioncharts/fusioncharts.charts
//= require maskedinput
//= require masks
//= require progressbar
//= require layout
//= require_tree .

APPLICATION.CSS
 *= require_self
 *= require sweetalert2
 *= require font-awesome
 *= require_tree .
 */

RAILS VERSION
Rails 5.1.7
RUBY VERSION
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

GEM FILE
gem 'sweetify'
gem 'rails-assets-sweetalert2', '~> 5.1.1', source: 'https://rails-assets.org'
gem 'sweet-alert2-rails'

Do you know what more can i do to fix it? thanks!

**Comment by Atrox** [comment]
Could you check if `window.Swal` is available on your page? It looks like there is an issue with your sweetalert2 installation.

**Comment by ademir10** [comment]
Thank you for the tip, Atrox! I'll try to install again this gem.
When you say: "Could you check if window.Swal is available on your page?" 
Sorry, but where can i check it? when i inspect the page on browser?
thanks!

**Comment by Atrox** [comment]
Exactly, check in the browser, in your console if the `window.Swal` object is available. Maybe there is just a timing problem?

**Comment by ademir10** [comment]
Now it's working but only if i add this another Gem: gem 'sweetalert2'
But my message it's a little small
In another projects i'm using your gem and everything is working fine.

Look the difference between the alerts in the pictures atached:
![Captura de Tela 2019-08-07 às 09 26 05](https://user-images.githubusercontent.com/2720896/62625307-50002680-b8fb-11e9-9177-8b68309cc679.png)
![Captura de Tela 2019-08-07 às 10 04 48](https://user-images.githubusercontent.com/2720896/62625310-50002680-b8fb-11e9-9701-df4e28c44558.png)

**Comment by Atrox** [comment]
These are the different sweetalert versions. You have different versions in your apps, so they look different ;).

**Comment by ademir10** [comment]
humm. let me check the difference between the versions in both projects, thank you man!
